# Generated by Django 5.1.6 on 2025-04-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tutorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='subjects',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
