# Generated by Django 5.1.6 on 2025-05-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='subjects',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
