# Generated by Django 5.1.6 on 2025-05-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_tutorprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='subjects',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
